### ISSUE TITLE
Gallery - Need image names in the listing

### ISSUE THREAD

**Issue by huntercross** [ponticlaro/bebop#54]
I think it would be very important to have the image's name (sanitized of course) in the listing when sorting. Often, I am uploading something in a particular order...say 001.jpg, 002.jpg...It would be nice to have that in the sort so I can make sure everything is in the right order...

![screen shot 2015-01-08 at 11 57 jan 8](https://cloud.githubusercontent.com/assets/2048577/5675998/5dc6a5bc-9792-11e4-9231-8bad0295c1f7.png)

![screen shot 2015-01-08 at 11 59 jan 8](https://cloud.githubusercontent.com/assets/2048577/5676000/6ccdff2e-9792-11e4-8f2f-37dc6a947253.png)

**Comment by cristianobaptista** [comment]
I checked the project code and if you do not replace the default reorder view for list items, it will display the image name while reordering.

Closing this one.
