### ISSUE TITLE
Versioning of the object json

### ISSUE THREAD

**Issue by huntercross** [ponticlaro/bebop#6]
This is more of a discussion than anything, but I think it would be fruitful to figure out some way to have the version of the library included in some way that could be checked later.

This way, within the data, there is some reference to which version of bebop created it. Then, if we have a mismatched set of versions, there might be a way to update the data to a version of the object model that we have in mind.

i.e. just for sake of argument, let's say we changed one parameter's name from "red" to "blue", then we would want to know that 1.0 uses red and 1.1 uses blue, since we are pushing the data as one json blob into the database

**Comment by cristianobaptista** [comment]
Moved to https://github.com/ponticlaro/bebop-core/issues/3
